# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e06385bb585290bace07b02cb10d9f5ce7f0e6996d6b50b89ff66eaa6ba1902f19c68a3cacfe9562ac584cb8fb00b2491bb0f3846acb813c8fb656ca95d3516f

test:
  secret_key_base: 3322b50208b6cdee156181a64adff6c8f33915fc4289a58ef4917ee4c1ff3d67bd44df5fc54eed67c7c2c449f87871f19d0da7a21fd97609591ef77549b22d34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
